[pytest]
testpaths = bdd_project/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
markers =
    api: API tests
    web: Web UI tests
    windows: Windows desktop tests
    macos: macOS desktop tests
    android: Android mobile tests
    iphone: iOS mobile tests
    tui: Terminal UI tests
    linux: Linux desktop tests
